on: ["push", "pull_request"]

name: Test1 Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: npm install, make test-coverage
      run: |
        npm install
        npm run coveralls

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
